### PR TITLE
Enforce html5 comment parsing precedence in RCDATA and RAWTEXT states

### PR DESCRIPTION
**Pull request by adon-at-work**
This PR is meant to enforce the HTML 5 comment parsing precedence in RCDATA and RAWTEXT states.

Consider `<style><!--</style>--></style>`, html 5 treats  as comment. By escaping `<!` to `&lt;!`, we can enforce that all browsers will be aligned in parsing. Therefore, `<!--` (or equivalently `&lt;!--`) is in RAWTEXT state.
In addition, we treat `<%` similarly, as it is an alternative comment tag recognized by at least IE.

The same logic is applied to RAWTEXT state.

### CODE REVIEW

**Comment by yahoocla** [comment]
CLA is valid!

**Comment by adon-at-work** [comment]
@neraliu and @yukinying , please review this and confirm that you've the same understanding on such handling. If okay, please merge. thanks.

**Comment by yukinying** [comment]
Yes this is one of the fundamental difference on HTML5 vs HTML4 as we discussed via email previously.

**Comment by yukinying** [comment]
Just note that the `nextPotentialState` is discussed in https://github.com/yahoo/secure-handlebars/pull/42#issuecomment-96863724 .

**Comment by adon-at-work** [comment]
you see my response there?

**Comment by yukinying** [comment]
Definitely. I think some of those changes may need to be done upstream at [context parser](https://github.com/yahoo/context-parser) as well. Sounds like a todo item.

**Pull request merged**
