### PR TITLE
fix the unit test for strict css parser

### PR DESCRIPTION
**Pull request by neraliu**
- add back jison as devDependency
- fix the unit test with strict css parser enable
- add the newly build of strict css parser

### CODE REVIEW

**Comment by yahoocla** [comment]
CLA is valid!

**Comment by adon-at-work** [comment]
please fix the issue regarding capital letter matching of `url`

**Comment by neraliu** [comment]
@adon-at-work, it is revised

**Comment by neraliu** [comment]
please note the original test case has covered the capital URL already

**Comment by adon-at-work** [comment]
gd to go

**Pull request merged**
